version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ltd_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - ltd_network
    depends_on:
      - mysql
      - redis

  nginx:
    image: nginx:alpine
    container_name: ltd_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - ltd_network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: ltd_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laboratorio_db
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_USER: ltd_user
      MYSQL_PASSWORD: ltd_password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - ltd_network

  redis:
    image: redis:7-alpine
    container_name: ltd_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ltd_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ltd_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: ltd_user
      PMA_PASSWORD: ltd_password
    ports:
      - "8081:80"
    networks:
      - ltd_network
    depends_on:
      - mysql

networks:
  ltd_network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
